SET MODE = MYSQL;

DROP TABLE IF EXISTS purchase_claim, sale_claim, car, seller;

CREATE TABLE car (id BIGINT NOT NULL AUTO_INCREMENT, number VARCHAR(10) NOT NULL, color VARCHAR(10) NOT NULL, YEAR INT(4) NOT NULL, brand VARCHAR(10) NOT NULL, PRIMARY KEY (id));

CREATE TABLE seller (id BIGINT NOT NULL AUTO_INCREMENT, email VARCHAR(50) NOT NULL, PRIMARY KEY(id));

CREATE TABLE sale_claim (id BIGINT NOT NULL AUTO_INCREMENT, car_id BIGINT NOT NULL, price BIGINT NOT NULL CHECK(price>0), seller_id BIGINT NOT NULL, status VARCHAR(10) NOT NULL DEFAULT 'open', PRIMARY KEY (id), FOREIGN KEY (car_id) REFERENCES car(id), FOREIGN KEY (seller_id) REFERENCES seller(id));

CREATE TABLE purchase_claim (id BIGINT NOT NULL AUTO_INCREMENT, car_id BIGINT NOT NULL, price BIGINT NOT NULL CHECK(price>0), status VARCHAR(10) NOT NULL DEFAULT 'active', sale_claim_id BIGINT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (car_id) REFERENCES car(id), FOREIGN KEY (sale_claim_id) REFERENCES sale_claim(id) ON DELETE CASCADE);